services:
  backend:
    image: floris-backend
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - database

  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - floris:/var/lib/postgresql/data
    env_file:
      - path: .env

volumes:
  floris: